version: "3.3"
services:
  redis:
    image: redis:6-alpine
    container_name: lila_redis
    ports:
      - 6379:6379

  lila:
#    image: konstanteenn/lichess-kube:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:9663
    container_name: lila
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - LILA_IP=${LILA_IP:-localhost}
      - LILA_WS_IP=${LILA_WS_IP:-localhost:9664}
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb?appName=lila}
      - REDIS_URI=${REDIS_URI:-redis://redis}


